/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: cebbd7b7b345476ef51e87d436f781a9)
interface __BaseEnv_CloudflareEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
