/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv ./cloudflare-env.d.ts` (hash: 7b162df716876019a3c44a6e405addda)
interface __BaseEnv_CloudflareEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	EMAIL_TRANSPORT: string;
	EMAIL_FROM: string;
	BETTER_AUTH_URL: string;
	WORKER_SELF_REFERENCE: Fetcher /* albayan-staging */ | Service<typeof import("./.open-next/worker").default>;
	IMAGES?: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		EMAIL_TRANSPORT: string;
		EMAIL_FROM: string;
		BETTER_AUTH_URL: string;
		WORKER_SELF_REFERENCE: Fetcher /* albayan-staging */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_TRANSPORT" | "EMAIL_FROM" | "BETTER_AUTH_URL">> {}
}
